export const Role = {
  SUPER_ADMIN: "SUPER_ADMIN" as any,
  DISTRICT_ADMIN: "DISTRICT_ADMIN" as any,
  BENEFICIARY_AGENCY: "BENEFICIARY_AGENCY" as any,
  COMPANY_ADMIN: "COMPANY_ADMIN" as any,
  COMPANY_MEMBER: "COMPANY_MEMBER" as any,
  NGO_ADMIN: "NGO_ADMIN" as any,
  NGO_MEMBER: "NGO_MEMBER" as any,
  PORTAL_ADMIN: "PORTAL_ADMIN" as any,
  CSR_ADMIN: "CSR_ADMIN" as any,
  ANALYST_REVIEWER: "ANALYST_REVIEWER" as any,
  COMPLIANCE_REVIEWER: "COMPLIANCE_REVIEWER" as any,
  FINANCE_USER: "FINANCE_USER" as any,
  APPROVER: "APPROVER" as any,
  AUDITOR: "AUDITOR" as any,
  AUTHORIZED_SIGNATORY: "AUTHORIZED_SIGNATORY" as any,
  CSR_RELATIONSHIP_MANAGER: "CSR_RELATIONSHIP_MANAGER" as any,
  JOINT_SECRETARY: "JOINT_SECRETARY" as any,
  PLANNING_SECRETARY: "PLANNING_SECRETARY" as any,
  DISTRICT_NODAL_OFFICER: "DISTRICT_NODAL_OFFICER" as any,
  STATE_CSR_CELL: "STATE_CSR_CELL" as any,
  CORPORATE_USER: "CORPORATE_USER" as any,
  IMPLEMENTING_AGENCY_USER: "IMPLEMENTING_AGENCY_USER" as any,
  GOVERNMENT_OFFICER: "GOVERNMENT_OFFICER" as any
};

export type Role = any;
