/** Shared default SLA values. Runtime values are overridden by Super Admin. */
export const SLA_TIMELINES = {
  RM_RESPONSE: 5,
  FEASIBILITY_REVIEW: 12,
  GRACE_PERIOD_BEFORE_ESCALATION: 2,
  JS_DECISION: 7,
  JS_ESCALATED_RESPONSE: 3,
  SECRETARY_ESCALATION: 2,
  GOVERNMENT_PITCH_VERIFICATION: 5,
  GRIEVANCE_LEVEL_1: 15,
  GRIEVANCE_LEVEL_2: 30,
  STATIC_HELPDESK: 2,
  NODAL_ASSIGNMENT: 2,
  FIELD_OFFICER_ASSIGNMENT: 3,
} as const;
